import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Authentication","description":"All API requests require a Bearer token.","frontmatter":{"title":"Authentication","description":"All API requests require a Bearer token."},"headers":[],"relativePath":"authentication.md","filePath":"authentication.md"}');
const _sfc_main = { name: "authentication.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="authentication" tabindex="-1">Authentication <a class="header-anchor" href="#authentication" aria-label="Permalink to &quot;Authentication&quot;">​</a></h1><h2 id="api-keys" tabindex="-1">API Keys <a class="header-anchor" href="#api-keys" aria-label="Permalink to &quot;API Keys&quot;">​</a></h2><p>All requests to the COGEXT API must include your API key as a Bearer token in the <code>Authorization</code> header.</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">Authorization:</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> Bearer</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> cg_live_YOUR_KEY</span></span></code></pre></div><p>Keys starting with <code>cg_live_</code> are production keys. Keep them secret — never commit them to source control or expose them client-side.</p><h2 id="getting-a-key" tabindex="-1">Getting a key <a class="header-anchor" href="#getting-a-key" aria-label="Permalink to &quot;Getting a key&quot;">​</a></h2><p>Sign in at <a href="https://app.cogextai.com" target="_blank" rel="noreferrer">app.cogextai.com</a> → <strong>Settings → API Keys → Create new key</strong>.</p><h2 id="example-request" tabindex="-1">Example request <a class="header-anchor" href="#example-request" aria-label="Permalink to &quot;Example request&quot;">​</a></h2><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">curl</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> https://api.cogextai.com/api/v1/commitments</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  -H</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &quot;Authorization: Bearer cg_live_abc123xyz&quot;</span></span></code></pre></div><h2 id="error-codes" tabindex="-1">Error codes <a class="header-anchor" href="#error-codes" aria-label="Permalink to &quot;Error codes&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Code</th><th>Meaning</th></tr></thead><tbody><tr><td><code>401</code></td><td>Missing or invalid API key</td></tr><tr><td><code>403</code></td><td>Valid key but insufficient permissions</td></tr><tr><td><code>429</code></td><td>Rate limit exceeded — back off and retry</td></tr></tbody></table><h2 id="rate-limits" tabindex="-1">Rate limits <a class="header-anchor" href="#rate-limits" aria-label="Permalink to &quot;Rate limits&quot;">​</a></h2><p>Production keys are rate-limited per minute. The response headers include:</p><table tabindex="0"><thead><tr><th>Header</th><th>Description</th></tr></thead><tbody><tr><td><code>X-RateLimit-Limit</code></td><td>Requests allowed per minute</td></tr><tr><td><code>X-RateLimit-Remaining</code></td><td>Requests remaining this window</td></tr><tr><td><code>X-RateLimit-Reset</code></td><td>Unix timestamp when the window resets</td></tr></tbody></table><div class="warning custom-block"><p class="custom-block-title">Keep keys secret</p><p>Never expose your API key in client-side code, public repositories, logs, or error messages. Rotate a compromised key immediately from the dashboard.</p></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("authentication.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const authentication = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  authentication as default
};
